source 'https://github.com/Artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

pod 'SDWebImage'
pod 'Masonry'
pod 'XLFBaseModelKit', :git => 'https://github.com/MarkeJave/XLFBaseModelKit.git', :tag => '1.0.0'
pod 'ASIKit', :git => 'https://github.com/MarkeJave/ASIKit.git', :tag => '1.0.0'
pod 'XLFBaseViewControllerKit', :git => 'https://github.com/MarkeJave/XLFBaseViewControllerKit.git', :tag => '1.0.0'
pod 'XLFBaseHttpRequestKit', :git => 'https://github.com/MarkeJave/XLFBaseHttpRequestKit.git', :tag => '1.0.0'
pod 'XLFKeyboardManagerKit', :git => 'https://github.com/MarkeJave/XLFKeyboardManagerKit.git', :tag => '1.0.0'
pod 'XLFCommonKit', :git => 'https://github.com/MarkeJave/XLFCommonKit.git', :tag => '1.0.1'
pod 'XLFViewControllerAnimationKit', :git => 'https://github.com/MarkeJave/XLFViewControllerAnimationKit.git', :tag => '1.0.0'
